# Site settings
title: Wallit Developer Documentation
baseurl: /documentation

# Build settings
markdown: kramdown
exclude: ['README.md']
sass:
    sass_dir: _sass

kramdown:
  input: GFM
  
defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"